### ISSUE TITLE
potential bug in fsm.hpp 

### ISSUE THREAD

**Issue by mathisloge** [p-groarke/fea_state_machines#2]
Hey,
first of all great fsm's.  I've read your article on isocpp.

If you enable FEA_FSM_NOTHROW the assert statement should be 

`std::get<size_t(Transition)>(_transitions) != StateEnum::count`

or maybe even better with a message? 
`assert(("fsm_state : unhandled transition", std::get<size_t(Transition)>(_transitions) != StateEnum::count));`

https://github.com/p-groarke/fea_state_machines/blob/master/include/fea_state_machines/fsm.hpp#L137

**Comment by p-groarke** [comment]
Hey! Thx for reporting this, I'll take a look.

**Comment by p-groarke** [comment]
Fixed (and added new features).

Stay safe
