### ISSUE TITLE
Question regarding member function

### ISSUE THREAD

**Issue by mathisloge** [p-groarke/fea_state_machines#4]
> The machine now supports member function callbacks.
> When using member function callbacks, add an object pointer as the first argument to your callback, like you would with std::function.
> For example : fea::fsm_builder<my_transitions, my_states, void(MyObj*, bool, int)>
> Then, add events using references to your member function pointer : add_event<fsm_event::on_enter>(&MyObj::my_enter_func)

Regarding this: 
Before that, I've used member funtions like this: 
`add_event<fsm_event::on_enter>(std::bind(&MyObj::MyEnterFnc, this, std::placeholders::_1, std::placeholders::_2)); `

Do you know if there are some performance / memory differences between those two?

**Comment by p-groarke** [comment]
In terms of performance I highly doubt it, but I don't have a benchmark to back that up. If anything, `std::bind` would be slower (not the other way around).

The new way is just easier to read and to use imho.

**Comment by mathisloge** [comment]
thought so, too. But I wasn't sure. Thanks.

I'm close this and read a little more about it.
